print("List Generator")
print("--------------")
print()
start = int(input("Start at: "))
print()
end = int(input("End before: "))
print()
step = int(input("Increment between values: "))
print()
print("List: ")
print()
for i in range(start,end,step):
  print(i)