print("=== Your Adventure Simulator ===")
print("""You'll be asked a bunch of questions then we'll make you up an amazing story with You as the satr! 😎""")
print()
name = input("Your name: ")
enemy = input("Your worst enemy's name: ")
superPower = input("Your super power: ")
place = input("Where you live?: ")
food = input("Your favourite food: ")
print()
print("Hello","\033[33m",name,"\033[0m","! Your ability to","\033[35m",superPower,"\033[0m","will make sure you  never have to look at","\033[31m",enemy,"\033[0m","again.Go eat","\033[36m",food,"\033[0m","as you walk down the streets of","\033[32m",place,"\033[0m","and use","\033[35m",superPower,"\033[0m","for good and not evil!")